// Automatically generated by MockGen. DO NOT EDIT!
// Source: vendor/github.com/aws/aws-sdk-go-v2/service/codebuild/codebuildiface/interface.go

package mock

import (
	codebuild "github.com/aws/aws-sdk-go-v2/service/codebuild"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CodeBuildAPI interface
type MockCodeBuildAPI struct {
	ctrl     *gomock.Controller
	recorder *_MockCodeBuildAPIRecorder
}

// Recorder for MockCodeBuildAPI (not exported)
type _MockCodeBuildAPIRecorder struct {
	mock *MockCodeBuildAPI
}

func NewMockCodeBuildAPI(ctrl *gomock.Controller) *MockCodeBuildAPI {
	mock := &MockCodeBuildAPI{ctrl: ctrl}
	mock.recorder = &_MockCodeBuildAPIRecorder{mock}
	return mock
}

func (_m *MockCodeBuildAPI) EXPECT() *_MockCodeBuildAPIRecorder {
	return _m.recorder
}

func (_m *MockCodeBuildAPI) BatchDeleteBuildsRequest(_param0 *codebuild.BatchDeleteBuildsInput) codebuild.BatchDeleteBuildsRequest {
	ret := _m.ctrl.Call(_m, "BatchDeleteBuildsRequest", _param0)
	ret0, _ := ret[0].(codebuild.BatchDeleteBuildsRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) BatchDeleteBuildsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BatchDeleteBuildsRequest", arg0)
}

func (_m *MockCodeBuildAPI) BatchGetBuildsRequest(_param0 *codebuild.BatchGetBuildsInput) codebuild.BatchGetBuildsRequest {
	ret := _m.ctrl.Call(_m, "BatchGetBuildsRequest", _param0)
	ret0, _ := ret[0].(codebuild.BatchGetBuildsRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) BatchGetBuildsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BatchGetBuildsRequest", arg0)
}

func (_m *MockCodeBuildAPI) BatchGetProjectsRequest(_param0 *codebuild.BatchGetProjectsInput) codebuild.BatchGetProjectsRequest {
	ret := _m.ctrl.Call(_m, "BatchGetProjectsRequest", _param0)
	ret0, _ := ret[0].(codebuild.BatchGetProjectsRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) BatchGetProjectsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BatchGetProjectsRequest", arg0)
}

func (_m *MockCodeBuildAPI) CreateProjectRequest(_param0 *codebuild.CreateProjectInput) codebuild.CreateProjectRequest {
	ret := _m.ctrl.Call(_m, "CreateProjectRequest", _param0)
	ret0, _ := ret[0].(codebuild.CreateProjectRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) CreateProjectRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateProjectRequest", arg0)
}

func (_m *MockCodeBuildAPI) CreateWebhookRequest(_param0 *codebuild.CreateWebhookInput) codebuild.CreateWebhookRequest {
	ret := _m.ctrl.Call(_m, "CreateWebhookRequest", _param0)
	ret0, _ := ret[0].(codebuild.CreateWebhookRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) CreateWebhookRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateWebhookRequest", arg0)
}

func (_m *MockCodeBuildAPI) DeleteProjectRequest(_param0 *codebuild.DeleteProjectInput) codebuild.DeleteProjectRequest {
	ret := _m.ctrl.Call(_m, "DeleteProjectRequest", _param0)
	ret0, _ := ret[0].(codebuild.DeleteProjectRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) DeleteProjectRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteProjectRequest", arg0)
}

func (_m *MockCodeBuildAPI) DeleteWebhookRequest(_param0 *codebuild.DeleteWebhookInput) codebuild.DeleteWebhookRequest {
	ret := _m.ctrl.Call(_m, "DeleteWebhookRequest", _param0)
	ret0, _ := ret[0].(codebuild.DeleteWebhookRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) DeleteWebhookRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteWebhookRequest", arg0)
}

func (_m *MockCodeBuildAPI) InvalidateProjectCacheRequest(_param0 *codebuild.InvalidateProjectCacheInput) codebuild.InvalidateProjectCacheRequest {
	ret := _m.ctrl.Call(_m, "InvalidateProjectCacheRequest", _param0)
	ret0, _ := ret[0].(codebuild.InvalidateProjectCacheRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) InvalidateProjectCacheRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "InvalidateProjectCacheRequest", arg0)
}

func (_m *MockCodeBuildAPI) ListBuildsRequest(_param0 *codebuild.ListBuildsInput) codebuild.ListBuildsRequest {
	ret := _m.ctrl.Call(_m, "ListBuildsRequest", _param0)
	ret0, _ := ret[0].(codebuild.ListBuildsRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) ListBuildsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListBuildsRequest", arg0)
}

func (_m *MockCodeBuildAPI) ListBuildsForProjectRequest(_param0 *codebuild.ListBuildsForProjectInput) codebuild.ListBuildsForProjectRequest {
	ret := _m.ctrl.Call(_m, "ListBuildsForProjectRequest", _param0)
	ret0, _ := ret[0].(codebuild.ListBuildsForProjectRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) ListBuildsForProjectRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListBuildsForProjectRequest", arg0)
}

func (_m *MockCodeBuildAPI) ListCuratedEnvironmentImagesRequest(_param0 *codebuild.ListCuratedEnvironmentImagesInput) codebuild.ListCuratedEnvironmentImagesRequest {
	ret := _m.ctrl.Call(_m, "ListCuratedEnvironmentImagesRequest", _param0)
	ret0, _ := ret[0].(codebuild.ListCuratedEnvironmentImagesRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) ListCuratedEnvironmentImagesRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListCuratedEnvironmentImagesRequest", arg0)
}

func (_m *MockCodeBuildAPI) ListProjectsRequest(_param0 *codebuild.ListProjectsInput) codebuild.ListProjectsRequest {
	ret := _m.ctrl.Call(_m, "ListProjectsRequest", _param0)
	ret0, _ := ret[0].(codebuild.ListProjectsRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) ListProjectsRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ListProjectsRequest", arg0)
}

func (_m *MockCodeBuildAPI) StartBuildRequest(_param0 *codebuild.StartBuildInput) codebuild.StartBuildRequest {
	ret := _m.ctrl.Call(_m, "StartBuildRequest", _param0)
	ret0, _ := ret[0].(codebuild.StartBuildRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) StartBuildRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StartBuildRequest", arg0)
}

func (_m *MockCodeBuildAPI) StopBuildRequest(_param0 *codebuild.StopBuildInput) codebuild.StopBuildRequest {
	ret := _m.ctrl.Call(_m, "StopBuildRequest", _param0)
	ret0, _ := ret[0].(codebuild.StopBuildRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) StopBuildRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StopBuildRequest", arg0)
}

func (_m *MockCodeBuildAPI) UpdateProjectRequest(_param0 *codebuild.UpdateProjectInput) codebuild.UpdateProjectRequest {
	ret := _m.ctrl.Call(_m, "UpdateProjectRequest", _param0)
	ret0, _ := ret[0].(codebuild.UpdateProjectRequest)
	return ret0
}

func (_mr *_MockCodeBuildAPIRecorder) UpdateProjectRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateProjectRequest", arg0)
}
